name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Zip up build result
      uses: montudor/action-zip@v1.0.0
      with:
        args: zip -qq -r build.zip dist/
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.0
      with:
          name: build-results.zip
          path: build.zip
